# Generated by Django 5.2.14 on 2026-05-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('duracao', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
