# Generated by Django 5.2.14 on 2026-05-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_remove_cliente_email_remove_cliente_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/'),
        ),
    ]
