# Generated by Django 5.2.14 on 2026-05-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_alter_cliente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_inicio', models.ImageField(blank=True, null=True, upload_to='inicio/')),
            ],
        ),
    ]
