# Generated by Django 5.2.14 on 2026-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_configuracaosite'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='ativacao',
            field=models.BooleanField(default=True),
        ),
    ]
